/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_7ab780ecd1837f88___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___js_sys_8c759272e4c39e68___Array__web_sys_137aeb805fe952e2___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___js_sys_8c759272e4c39e68___Function_fn_wasm_bindgen_7ab780ecd1837f88___JsValue_____wasm_bindgen_7ab780ecd1837f88___sys__Undefined___js_sys_8c759272e4c39e68___Function_fn_wasm_bindgen_7ab780ecd1837f88___JsValue_____wasm_bindgen_7ab780ecd1837f88___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke___wasm_bindgen_7ab780ecd1837f88___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_7ab780ecd1837f88___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
