/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h13a68024a1cb6744: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h58242b11f8640c79: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h840a92fa88ffd918: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4f9d34c98d5c1044: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2514708e156f131c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd6f43efc9dc13fac: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h22863016ef2e2e67: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
