/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h053cfa2ae71345c0: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hdb0d90046bb71a07: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fd74d744f8ba2de: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2e39984c5690b1bb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ebc08692a558566_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd1528c7a992371e7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h77d5085b43f828b4: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
