/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfe71eb28ee990786: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hed71664b85e64807: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha7d2a2b57f8309e1: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h22b98e27ae981c23: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h035748d492671871_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1bc097703feb38ea: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6acd00059eec22fd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
