/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h54c5ef0285851dc0: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h698a58ec60ac8c0c: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h709f70db6b0af24b: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5770e4f6df08492d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h276cfbcbdbf4afb5_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd0a4e5ecc651b732: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h17292cd520d31c19: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
