/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_main: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hbdba16bb5fe57f06: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hdc466ff1675c8cf5: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4f0480fbf9143d01: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h90b1b3d6bd981e7e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h36dd65c0b3a100fa_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__he48c4e1e3f66f59d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3b0d9d511d6ccc50: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
